name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.2
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        files: /**/*.xml
        report_individual_runs: true
        deduplicate_classes_by_file_name: false

    - name: Publish
      run: dotnet publish petshop/petshop.csproj --configuration Release --output outpath --no-restore --verbosity normal

    - uses: actions/upload-artifact@v2
      with:
       name: upload artifact
       path: petshop/outpath/ # or path/to/artifact
      # Deploy to Azure Web apps
        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: cie-demo-web # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: 'petshop/outpath'
